"""Create cities, city_scores, shortlist_items and itineraries tables

Revision ID: afd5d20a644f
Revises: 
Create Date: 2026-10-09 12:36:25.179969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afd5d20a644f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('wiki_title', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_sample_data', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('score_source', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('latitude IS NULL OR (latitude >= -90 AND latitude <= 90)', name='ck_cities_latitude_range'),
    sa.CheckConstraint('longitude IS NULL OR (longitude >= -180 AND longitude <= 180)', name='ck_cities_longitude_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'country', name='uq_cities_name_country')
    )
    op.create_table('city_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.String(length=64), nullable=False),
    sa.Column('metric_id', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.CheckConstraint("metric_id IN ('HOUSING', 'COST_OF_LIVING', 'STARTUPS', 'VENTURE_CAPITAL', 'TRAVEL_CONNECTIVITY', 'COMMUTE', 'BUSINESS_FREEDOM', 'SAFETY', 'HEALTHCARE', 'EDUCATION', 'ENVIRONMENTAL_QUALITY', 'ECONOMY', 'TAXATION', 'INTERNET_ACCESS', 'LEISURE_CULTURE', 'TOLERANCE', 'OUTDOORS')", name='ck_city_scores_metric_id'),
    sa.CheckConstraint('score >= 0 AND score <= 10', name='ck_city_scores_score_range'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'metric_id', name='uq_city_scores_city_metric')
    )
    op.create_table('itineraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('city_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("title <> ''", name='ck_itineraries_title_not_empty'),
    sa.CheckConstraint('end_date >= start_date', name='ck_itineraries_dates'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.create_index('ix_itineraries_owner_id', ['owner_id'], unique=False)

    op.create_table('shortlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('city_id', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('position >= 1', name='ck_shortlist_position_positive'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'city_id', name='uq_shortlist_owner_city')
    )
    with op.batch_alter_table('shortlist_items', schema=None) as batch_op:
        batch_op.create_index('ix_shortlist_items_owner_id', ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shortlist_items', schema=None) as batch_op:
        batch_op.drop_index('ix_shortlist_items_owner_id')

    op.drop_table('shortlist_items')
    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.drop_index('ix_itineraries_owner_id')

    op.drop_table('itineraries')
    op.drop_table('city_scores')
    op.drop_table('cities')
    # ### end Alembic commands ###
